### ISSUE TITLE
Year 4/OME Algorithm Error

### ISSUE THREAD

**Issue by kylehodgetts** [markormesher/cs-notes#3]
On page 10 where Bellman Ford is illustrated, the algorithm contains the return true statement, indicating no negative cycles, inside the for loop when it should be outside, meaning it returns true after every edge has been checked.

Currently
```
fun BELLMAN􀀀FORD(G, w, s):
2
3 // run initialisation and relaxation:
4 INITIALISE(G, s)
5 for i from 1 to n 􀀀 1, do:
6   for each edge (u, v) in G, do:
7     RELAX(u, v, w)
8
9 // determine outcome:
10 for each edge (u, v) in G, do:
11   if (d[v] > d[u] + w(u, v)):
12     return FALSE // negative cycle reachable from s
13 else:
14     return TRUE
```

Should be:
```
fun BELLMAN􀀀FORD(G, w, s):
2
3 // run initialisation and relaxation:
4 INITIALISE(G, s)
5 for i from 1 to n 􀀀 1, do:
6   for each edge (u, v) in G, do:
7     RELAX(u, v, w)
8
9 // determine outcome:
10 for each edge (u, v) in G, do:
11   if (d[v] > d[u] + w(u, v)):
12     return FALSE // negative cycle reachable from s
13 return TRUE
```

**Comment by markormesher** [comment]
Yeah, loads of tabs got screwed up in the last edit for some reason, so there are a few issues like this. I've got a list of them to fix on Wednesday (when I'll next be doing OME). I'll close this when I fix them. Thanks for pointing it out :)
